openapi: 3.0.0
info:
  title: alticci API
  description: Calculate the Alticci sequence.
  version: 0.1.0
servers:
  - url:  http://localhost:8080/AlticciApplication/webresources/api
paths:
  /alticci/{n}:
    get:
      summary: Returns a value from the Alticci sequence.
      responses:
        '200':
          description: the Alticci sequence
          content:
            application/TEXT_PLAIN:
              schema:
                type: integer
      parameters:
        - name: n
          in: path
          required: true
          description: the sequence number
          content:
            application/TEXT_PLAIN:
              schema:
                type: integer
        
