# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.
FROM java:8  
COPY AlticciApplication.war E:\Work\apache-tomcat-9.0.64\webapps\AlticciApplication.war
EXPOSE 8080
entrypoint ["java","-jar","/AlticciApplication.jar]